export const JOIN_LINK_NOT_FOUND = 'JOIN_LINK_NOT_FOUND';
export const JOIN_LINK_REVOKED = 'JOIN_LINK_REVOKED';
export const JOIN_LINK_EXPIRED = 'JOIN_LINK_EXPIRED';
export const SEAT_POOL_EXHAUSTED = 'SEAT_POOL_EXHAUSTED';
export const SEAT_ALREADY_CLAIMED = 'SEAT_ALREADY_CLAIMED';
export const CONTRACT_NOT_ACTIVE = 'CONTRACT_NOT_ACTIVE';
export const ACCOUNT_EXISTS = 'ACCOUNT_EXISTS';
