import { mkdirSync, writeFileSync } from 'node:fs';

const DIR = '.scratch/phase-6-ai-enterprise/issues';
mkdirSync(DIR, { recursive: true });

const tickets = [
  {
    n: '01', slug: 'model-provider-port',
    title: 'The model provider is a port, not a client',
    build: 'A `MODEL_PROVIDER` token and interface, mirroring `EXECUTION_PROVIDER` from Phase 5. One HTTP implementation calls Anthropic; tests substitute a recording stub through `createTestApp`. Every AI feature depends on the interface and never on the SDK directly.',
    caution: '**Stubbing at the service boundary would leave the pipeline untested, and the pipeline is where the defects are.** The stub replaces the outbound call only — retrieval, prompt assembly, queueing, parsing and persistence must all run for real in tests.',
    blocked: 'nothing',
    acs: [
      'A `MODEL_PROVIDER` token resolves to an HTTP implementation in the running application',
      'A test can substitute a stub through the existing `createTestApp` provider-override list',
      'The interface carries the model identifier, so per-feature model choice is a caller decision',
      'No feature module imports an Anthropic SDK type directly',
      'A provider error surfaces as a typed failure, not an unhandled rejection',
    ],
  },
  {
    n: '02', slug: 'cost-attribution',
    title: 'Every model call records what it cost and who it was for',
    build: 'A usage record per call: feature, organisation, model, input tokens, output tokens, cache-read tokens, cache-write tokens. An owner-facing report aggregates by feature and by organisation over a period.',
    caution: '**An AI feature whose cost cannot be attributed cannot be managed.** Cache-read tokens are recorded as their own column because a zero cache-read rate is the specific failure this phase must be able to see.',
    blocked: '01',
    acs: [
      'Every model call writes a usage row carrying feature, organisation and model',
      'Input, output, cache-read and cache-write tokens are stored separately',
      'A call that fails still records the attempt and its feature',
      'The owner can read cost aggregated by feature and by organisation for a date range',
      'A student cannot read cost data through any path',
    ],
  },
  {
    n: '03', slug: 'prompt-caching',
    title: 'Prompt caching is a design constraint',
    build: 'Prompt assembly puts the stable grounding material first, behind a cache breakpoint, and the volatile part — the student\'s question, the timestamp, the attempt identifier — strictly after it. A deterministic assembly function is the single place prompts are built.',
    caution: '**Caching is a prefix match. Anything varying placed before the boundary silently invalidates it and multiplies cost, with no error and no visible symptom until the invoice arrives.** Ordering of retrieved material must be deterministic; an unsorted list is a varying prefix.',
    blocked: '01, 02',
    acs: [
      'Two questions against the same batch produce byte-identical prefixes',
      'Retrieved grounding material is ordered deterministically, not by map or set iteration',
      'No timestamp, request identifier or user identifier appears before the cache breakpoint',
      'The assembled prefix is exercised by a test that compares two real assemblies, not by inspection',
      'Cache-read tokens returned by the provider are recorded against the call',
    ],
  },
  {
    n: '04', slug: 'batch-api',
    title: 'Offline bulk work uses the batch path',
    build: 'A batch submission path for work that is not latency-sensitive — lecture summarisation and bulk question generation. Jobs are submitted, polled and reconciled through the Phase 1 queue.',
    caution: '**Batch work runs asynchronously at half cost, but it is a different failure mode: a batch can partially succeed.** Reconciliation must handle a batch where some items completed and others did not, without losing the completed ones or double-processing them.',
    blocked: '01, 02',
    acs: [
      'A bulk request is submitted as a batch rather than as N individual calls',
      'Polling and reconciliation happen on a repeating job, never inline with a request',
      'A partially completed batch persists the completed items and retries only the rest',
      'A reconciled item is never processed twice',
      'Batch usage is attributed the same way individual calls are',
    ],
  },
  {
    n: '05', slug: 'structured-output',
    title: 'Parsed responses are structured or rejected',
    build: 'Any response that is parsed rather than shown to a person — generated questions, extracted chapters, review verdicts, plan items — is requested as structured output against a declared shape and validated on arrival.',
    caution: '**Malformed output must be rejected, not coerced.** A half-parsed question that reaches the bank is worse than a failed generation, because the failure is silent and the artefact looks legitimate.',
    blocked: '01',
    acs: [
      'Every parsed feature declares its response shape',
      'A response failing the shape is rejected and recorded as a failure',
      'A rejected response persists nothing partial',
      'A rejected response is retried a bounded number of times, then gives up visibly',
      'Prose is never parsed with a regular expression to recover a field',
    ],
  },
  {
    n: '06', slug: 'degradation',
    title: 'A provider outage leaves the student on the human path',
    build: 'Every AI feature has a defined behaviour when the provider times out, errors or returns something unusable: the student sees a clear state and the human path remains open.',
    caution: '**The failure mode to avoid is a silent one.** A doubt that appears answered but is not, or a queue entry that never resolves, is worse than an honest "this could not be answered automatically — an instructor has been notified".',
    blocked: '01, 05',
    acs: [
      'A provider timeout on a doubt routes it to an instructor with a visible state',
      'A provider error never leaves a record stuck in a pending state indefinitely',
      'The student is told plainly that automation failed rather than shown an empty answer',
      'A failed generation for an instructor feature reports the failure rather than producing nothing',
      'Repeated provider failure does not retry without bound',
    ],
  },
  {
    n: '07', slug: 'grounding-retrieval',
    title: 'Grounding is scoped to what the asking student may access',
    build: 'Retrieval assembles context for a question from the organisation\'s own content — lesson text, transcript segments, notes and published doubt answers — restricted to batches the asking student is enrolled in.',
    caution: '**This is the highest-value test in the phase and it is a data-leak boundary.** Content from another organisation, or from a batch the student is not enrolled in, must be unreachable through retrieval even when it is the best textual match.',
    blocked: '01',
    acs: [
      'Retrieval returns content only from batches the asking student is enrolled in',
      'Content belonging to another organisation is never retrieved',
      'A student enrolled in one batch cannot surface another batch\'s lesson through a crafted question',
      'Retrieval draws on transcript segments as well as lesson text',
      'An unenrolled student retrieving against a batch gets nothing, not an error revealing the batch exists',
    ],
  },
  {
    n: '08', slug: 'doubt-answering',
    title: 'A doubt is answered immediately, with citations',
    build: 'Posting a doubt returns immediately with a pending state; a queued job answers it from retrieved course content and the answer arrives by notification, carrying citations to the lessons it drew on.',
    caution: '**The answer must return by notification, not by holding the request open.** Per the spec every AI call is a queued job; an answer computed inline is the mistake this phase is specifically told not to make.',
    blocked: '01, 03, 06, 07',
    acs: [
      'Posting a doubt returns immediately with a pending state',
      'The answer is produced by a queued job, never inline with the request',
      'The answer carries citations to the lessons it drew on',
      'The student is notified when the answer arrives',
      'An answer is grounded in retrieved content rather than the model\'s own knowledge',
    ],
  },
  {
    n: '09', slug: 'citation-integrity',
    title: 'Every citation resolves to a lesson the student may open',
    build: 'Before an answer is shown, each citation is checked against real, accessible lessons. An answer citing content the student cannot access is rejected rather than shown.',
    caution: '**A citation is a promise the student can follow.** A fabricated or inaccessible citation is both a broken promise and a leak signal — it tells the student that content exists which they cannot see.',
    blocked: '07, 08',
    acs: [
      'A citation pointing at a non-existent lesson causes the answer to be rejected',
      'A citation pointing at a lesson the student cannot access causes the answer to be rejected',
      'A rejected answer routes the doubt to a human rather than showing nothing',
      'Every citation shown resolves to a lesson the student can open',
      'Citation checking happens before the answer is visible, not after',
    ],
  },
  {
    n: '10', slug: 'answer-labelling',
    title: 'A student always knows whether they are reading a machine',
    build: 'Automated answers carry an explicit source marker distinguishing them from instructor answers, in the stored record and in every read path.',
    caution: '**The label must live on the record, not in the presentation layer.** A frontend that forgets to render it would otherwise present a machine answer as an instructor\'s.',
    blocked: '08',
    acs: [
      'An automated answer is marked as such on the stored record',
      'An instructor answer is distinguishable from an automated one in every read path',
      'An instructor editing a drafted reply produces an answer attributed to the instructor',
      'The marker cannot be set by a client',
      'A doubt answered automatically then escalated shows both, distinctly',
    ],
  },
  {
    n: '11', slug: 'escalation',
    title: 'Escalation is one action away and carries the automated answer',
    build: 'A student marks an answer unhelpful; the doubt reaches an instructor\'s inbox carrying the automated answer that did not help.',
    caution: '**The instructor must see what the student was already told.** Without it the instructor may contradict the automated answer unknowingly, which is worse for the student than no automation at all.',
    blocked: '08, 10',
    acs: [
      'Marking an answer unhelpful moves the doubt to an instructor inbox',
      'The escalated doubt carries the automated answer that was rejected',
      'The student is told a human has been reached',
      'Escalation is available on every automated answer, not only failed ones',
      'An escalated doubt cannot be answered automatically a second time',
    ],
  },
  {
    n: '12', slug: 'draft-replies',
    title: 'An escalated doubt arrives pre-drafted',
    build: 'On escalation, a queued job drafts a reply for the instructor. The instructor edits and sends; the sent answer is attributed to the instructor.',
    caution: '**The draft is for the instructor, never for the student.** A drafted reply must not be visible to the student until an instructor has committed it.',
    blocked: '11',
    acs: [
      'Escalation queues a draft reply for the instructor',
      'The draft is never visible to the student',
      'The instructor can discard the draft and write their own',
      'A sent reply is attributed to the instructor, not to automation',
      'A failed draft leaves the doubt answerable rather than blocked',
    ],
  },
  {
    n: '13', slug: 'unhelpful-signal',
    title: 'The unhelpful-answer set is a first-class report',
    build: 'Answers students marked unhelpful are collected and surfaced to the owner grouped by batch, subject and topic.',
    caution: '**This is the highest-value signal the AI layer produces and it is nearly free to collect.** It maps where content and teaching are weakest. Leaving it in a table unread is the failure mode the spec calls out.',
    blocked: '11',
    acs: [
      'Every unhelpful mark is recorded with the question, the answer and the context',
      'The owner can read them grouped by batch, subject and topic',
      'The report distinguishes an answer marked unhelpful from one that failed to generate',
      'An instructor can see the unhelpful set for their own batches',
      'A student cannot read another student\'s doubts through this report',
    ],
  },
  {
    n: '14', slug: 'question-generation',
    title: 'Questions are generated into an unreviewed state',
    build: 'An instructor generates draft questions from a lesson at a specified topic and difficulty. Drafts enter the Phase 3 bank marked unreviewed and mandatorily tagged.',
    caution: '**Tagging is mandatory, consistent with Phase 3\'s rule.** An untagged question is invisible to weak-topic mapping and practice generation, which is where the bank earns its value.',
    blocked: '01, 05',
    acs: [
      'An instructor generates drafts from a lesson at a chosen topic and difficulty',
      'Drafts enter the existing question bank rather than a parallel store',
      'Every generated question carries a subject and topic tag',
      'A generated question is marked unreviewed on creation',
      'A malformed generation persists no questions at all',
    ],
  },
  {
    n: '15', slug: 'review-gating',
    title: 'Unreviewed questions are unreachable by students',
    build: 'A generated question cannot be served through any student-facing path until an instructor approves it — not in a test, not in practice, not in a daily set.',
    caution: '**Every path must be closed, not the obvious one.** Phase 3 and Phase 4 added several independent ways a question reaches a student; each is a separate hole.',
    blocked: '14',
    acs: [
      'An unreviewed question cannot appear in a test',
      'An unreviewed question cannot appear in topic practice',
      'An unreviewed question cannot appear in a daily practice set',
      'Approving a question makes it servable and records who approved it',
      'An instructor can reject a generated question, and a rejected one never becomes servable',
    ],
  },
  {
    n: '16', slug: 'practice-generation',
    title: 'Gaps in the bank can be filled deliberately',
    build: 'An instructor requests practice problems at a target topic and difficulty; generation runs as bulk batch work and the results land unreviewed like any other generation.',
    caution: '**This is bulk work and belongs on the batch path**, not on N individual calls. It is not latency-sensitive and the cost difference is the point.',
    blocked: '04, 14, 15',
    acs: [
      'An instructor requests a count of problems at a target topic and difficulty',
      'Generation runs through the batch path rather than as individual calls',
      'Results enter the bank unreviewed and tagged',
      'The instructor is notified when a bulk generation completes',
      'A partially completed bulk generation keeps what succeeded',
    ],
  },
  {
    n: '17', slug: 'lecture-summaries',
    title: 'Every lecture gets a summary and timestamped chapters',
    build: 'From the transcripts Phase 4 already produces, derive a summary, key points and timestamped chapters. Runs as batch work at no additional transcription cost.',
    caution: '**Chapter timestamps must fall inside the lecture and be strictly increasing.** A chapter list that seeks past the end of the video, or backwards, is worse than none.',
    blocked: '04, 05',
    acs: [
      'A summary and key points are derived from an existing transcript',
      'Chapters carry timestamps that are strictly increasing',
      'No chapter timestamp falls outside the lecture duration',
      'A lesson with no transcript produces no summary rather than an empty one',
      'Summarisation uses the batch path and the cheaper model',
    ],
  },
  {
    n: '18', slug: 'code-review',
    title: 'Code review runs after the judge, never instead of it',
    build: 'A judged submission receives commentary on approach, complexity, naming and structure, alongside a complexity comparison with the reference solution.',
    caution: '**Test cases decide correctness; the model comments on quality.** A review that contradicts the verdict, or that is treated as a verdict, breaks the Phase 5 contract that the judge is authoritative.',
    blocked: '01, 05, 21',
    acs: [
      'Review runs only after a judged verdict exists',
      'Review never alters the verdict',
      'Commentary covers approach, complexity, naming and structure',
      'A failed review leaves the verdict and the submission intact',
      'Review is queued, not inline with submission',
    ],
  },
  {
    n: '19', slug: 'hints',
    title: 'Hints are graduated, bounded and recorded',
    build: 'A stuck student requests a hint. Hints escalate in specificity across a bounded number of steps, are rate-limited, and each use is recorded against the submission.',
    caution: '**A hint system that produces the answer on the fourth press is a solution system with extra steps.** The final hint must still stop short of the solution, and the bound must be enforced server-side.',
    blocked: '01, 05',
    acs: [
      'Hints escalate in specificity across a bounded sequence',
      'The bound is enforced by the server, not by the client hiding a button',
      'Every hint taken is recorded against the submission',
      'Hint requests are rate-limited independently of the run rate limit',
      'A hint never contains a complete working solution',
    ],
  },
  {
    n: '20', slug: 'project-feedback',
    title: 'Project feedback is drafted for a reviewer, not sent',
    build: 'An automated first pass on a project submission comments on readability and structure, and may suggest rubric scores. It is delivered to the reviewer.',
    caution: '**Drafted, not sent.** Per the spec, project feedback is for the reviewer. It must not reach the student until a human commits it, and a suggested rubric score is a suggestion until then.',
    blocked: '01, 05, 21',
    acs: [
      'An automated pass runs on submission and reaches the reviewer',
      'The draft is never visible to the student',
      'Suggested rubric scores are stored as suggestions, not as scores',
      'A reviewer can discard the draft entirely',
      'Committed feedback is attributed to the reviewer',
    ],
  },
  {
    n: '21', slug: 'marking-boundary',
    title: 'No automated path can commit a mark',
    build: 'A boundary test asserting that no AI-originated path writes a mark, a rubric score, a pass verdict or a certificate.',
    caution: '**Non-negotiable, and it extends the position already taken on plagiarism flags in Phase 5.** This ticket exists as its own test because the guarantee spans several modules and would otherwise be nobody\'s responsibility.',
    blocked: 'nothing',
    acs: [
      'No AI path writes to an awarded-marks column',
      'No AI path writes a committed rubric criterion score',
      'No AI path sets a project milestone to passed',
      'No AI path issues a certificate or a credential',
      'The assertion is a test that fails the build, not a convention',
    ],
  },
  {
    n: '22', slug: 'study-plans',
    title: 'A plan composed from goal, weakness, time and deadlines',
    build: 'A daily plan composed from the onboarding goal, the Phase 3 weak-topic map, Phase 4 spaced-repetition items, declared available time, and upcoming test dates.',
    caution: '**Achievable rather than aspirational.** A plan that ignores declared available time will be abandoned, and an abandoned plan is worse than none because it also costs a model call.',
    blocked: '01, 05',
    acs: [
      'The plan draws on the weak-topic map rather than on the syllabus order alone',
      'The plan respects declared available time',
      'An upcoming test date shifts the plan toward revision',
      'Spaced-repetition items due today appear in the plan',
      'A student with no history still gets a usable plan',
    ],
  },
  {
    n: '23', slug: 'plan-regeneration',
    title: 'Regeneration is scheduled, not on demand',
    build: 'Plans regenerate on a repeating job, adjusting when a student falls behind or races ahead.',
    caution: '**Stability is the feature.** A plan the student can regenerate at will is a plan they will reroll instead of following, and every reroll is a model call.',
    blocked: '22',
    acs: [
      'Regeneration runs on a repeating job',
      'A student cannot force regeneration on demand',
      'Falling behind shifts the plan rather than accumulating an impossible backlog',
      'Racing ahead pulls work forward',
      'A regeneration failure leaves the previous plan in place',
    ],
  },
  {
    n: '24', slug: 'sso',
    title: 'Single sign-on configured per corporate',
    build: 'Per-corporate sign-on configuration against mainstream institutional identity providers, with the provider\'s configuration stored per corporate rather than globally.',
    caution: '**This is frequently the item that unblocks a large deal, and it is comparatively small.** It has few dependencies beyond the Phase 1 account-merge mechanism.',
    blocked: 'nothing',
    acs: [
      'Sign-on configuration is stored per corporate, not globally',
      'Two corporates can use different providers simultaneously',
      'A misconfigured provider fails closed with a clear error',
      'Provider secrets are never returned through any read path',
      'A corporate administrator cannot configure sign-on for another corporate',
    ],
  },
  {
    n: '25', slug: 'account-linking',
    title: 'A returning student links rather than duplicating',
    build: 'First sign-in through an institutional provider links to the existing account by verified email, reusing the Phase 1 merge mechanism.',
    caution: '**A student who already has an account must not acquire a second one.** Duplicate accounts split enrolments, progress and payment history, and the damage is discovered long after the cause.',
    blocked: '24',
    acs: [
      'First sign-in with a matching verified email links to the existing account',
      'Linking reuses the Phase 1 merge mechanism rather than a parallel one',
      'An unverified email does not silently link',
      'A linked account keeps its existing enrolments and progress',
      'Signing in twice does not create a second link',
    ],
  },
  {
    n: '26', slug: 'authorisation-from-membership',
    title: 'Authentication is delegated; authorisation is not',
    build: 'Role and access continue to derive from membership and enrolment records, never from claims asserted by the institution\'s identity provider.',
    caution: '**An identity provider asserting a role must not be believed.** This is an authorisation boundary and warrants the same rigour as the Phase 1 access tests.',
    blocked: '24, 25',
    acs: [
      'A provider claiming an administrator role does not grant one',
      'Access derives from enrolment records after sign-in',
      'A provider claim cannot add a batch enrolment',
      'A revoked enrolment stays revoked across a fresh sign-on',
      'Role changes require the existing administrative path',
    ],
  },
  {
    n: '27', slug: 'integration-api',
    title: 'A scoped, credentialed, versioned integration API',
    build: 'A versioned API exposing attendance, results and progress for one corporate\'s own students, authenticated by credentials issued and revoked independently of any user account.',
    caution: '**A request beyond scope must be indistinguishable from a request for a record that does not exist.** A 403 where a 404 belongs tells an integrator that another corporate\'s student exists.',
    blocked: 'nothing',
    acs: [
      'Credentials are issued and revoked independently of user accounts',
      'A corporate\'s credentials reach only that corporate\'s students',
      'An out-of-scope record is indistinguishable from a missing one',
      'The API carries a version in its path',
      'A revoked credential stops working immediately',
    ],
  },
  {
    n: '28', slug: 'branded-portal',
    title: 'A corporate\'s students see the corporate\'s brand',
    build: 'Per-corporate branding — name, logo, colours — applied to what that corporate\'s students see.',
    caution: '**This is styling only. No data isolation is being claimed or enforced.** The organisation columns exist from Phase 1 and this ticket must not be read as making them an isolation boundary.',
    blocked: 'nothing',
    acs: [
      'Branding is configured per corporate',
      'A corporate\'s students receive that corporate\'s branding',
      'A student outside any corporate receives the platform default',
      'Branding configuration does not alter any access decision',
      'A corporate administrator cannot set branding for another corporate',
    ],
  },
  {
    n: '29', slug: 'event-capture',
    title: 'Funnel events are captured',
    build: 'Capture of page views, catalogue views, checkout starts and checkout completions — the events funnel analysis needs and which do not exist today.',
    caution: '**This does not exist and must be built before the funnel report can mean anything.** Capture must be cheap enough not to slow the pages it measures.',
    blocked: 'nothing',
    acs: [
      'Page views, catalogue views, checkout starts and completions are captured',
      'Capture never blocks the response it measures',
      'An event carries enough context to attribute it to a source',
      'Events are retained on a defined schedule rather than for ever',
      'A malformed event is dropped rather than failing the request',
    ],
  },
  {
    n: '30', slug: 'report-builder',
    title: 'A report is built from dimensions and measures',
    build: 'A defined palette of dimensions and measures the owner composes into a report — not arbitrary query access.',
    caution: '**Not arbitrary query access.** A report builder that accepts SQL is an injection surface and an availability risk; the palette is the security boundary.',
    blocked: 'nothing',
    acs: [
      'The owner composes a report from a defined dimension and measure palette',
      'A dimension outside the palette is rejected',
      'No client-supplied string reaches a query as SQL',
      'A report with no matching rows returns empty rather than erroring',
      'An expensive report is bounded rather than allowed to run unbounded',
    ],
  },
  {
    n: '31', slug: 'saved-reports',
    title: 'A saved report respects the viewer, not the author',
    build: 'Reports are saved, shared, scheduled through the existing queue, and exported. A shared report is evaluated against the viewer\'s scope.',
    caution: '**Scoping to the author is the obvious mistake and it is a data leak.** A report an owner shares with a corporate administrator must show that administrator only their own students.',
    blocked: '30',
    acs: [
      'A saved report is evaluated against the viewer\'s scope',
      'A corporate administrator viewing a shared report sees only their own corporate',
      'Scheduling reuses the existing job queue',
      'An export produces the same rows the viewer would see interactively',
      'Revoking a share stops access immediately',
    ],
  },
  {
    n: '32', slug: 'funnel-analysis',
    title: 'Where prospective students drop out',
    build: 'A funnel report over the captured events showing progression from view to catalogue to checkout start to completion, broken down by source.',
    caution: '**The report is only as honest as the capture.** A stage with no capture must read as unknown rather than as zero, or the owner will conclude the wrong thing about where the loss is.',
    blocked: '29, 30',
    acs: [
      'The funnel shows progression across the captured stages',
      'A stage with no data reads as unknown rather than zero',
      'The funnel breaks down by source',
      'A date range bounds the report',
      'The report is scoped to the viewer',
    ],
  },
  {
    n: '33', slug: 'retention-cohorts',
    title: 'Retention by joining month and by source',
    build: 'Cohort retention computed on a schedule and materialised, not computed per request.',
    caution: '**Computed per request this does not survive real data volume.** Materialisation is the design, not an optimisation to add later.',
    blocked: '29, 30',
    acs: [
      'Cohorts are computed on a repeating job and materialised',
      'A read serves materialised rows rather than recomputing',
      'Cohorts break down by joining month and by source',
      'A recomputation failure leaves the previous materialisation readable',
      'The report is scoped to the viewer',
    ],
  },
  {
    n: '34', slug: 'instructor-comparison',
    title: 'Instructors compared on evidence',
    build: 'A report comparing instructors on attendance, results and responsiveness across their batches.',
    caution: '**Responsiveness must be measured from real timestamps**, not from a field an instructor can set. A metric a subject can edit is not a metric.',
    blocked: '30',
    acs: [
      'The report covers attendance, results and responsiveness',
      'Responsiveness derives from recorded timestamps, not from editable fields',
      'An instructor with no batches appears rather than vanishing',
      'An instructor cannot read another instructor\'s comparison',
      'The report is bounded by a date range',
    ],
  },
  {
    n: '35', slug: 'page-builder',
    title: 'Landing pages composed from a defined block palette',
    build: 'A page composed from an ordered list of blocks drawn from a palette we define. Per `AUDIT.md` §8.2 the recommendation is a section builder — reorder, show and hide predefined sections — rather than free-form drag-and-drop.',
    caution: '**`specs/DECISIONS.md` records an unresolved conflict about whether the reference product\'s palette exists as documented. That conflict is resolved by defining our own palette, and the temptation to reverse-engineer theirs should be resisted.**',
    blocked: 'nothing',
    acs: [
      'A page is an ordered list of blocks from a defined palette',
      'A block kind outside the palette is rejected',
      'Blocks can be reordered, shown and hidden',
      'A draft page is not publicly readable until published',
      'Publishing is an explicit action, not a side effect of saving',
    ],
  },
  {
    n: '36', slug: 'blog-and-articles',
    title: 'Articles are published to rank',
    build: 'Article publishing on the existing blog module, with drafts, scheduling and publication.',
    caution: '**`cms` is 1,601 lines and 44 endpoints with no tests** per `AUDIT.md` §8.2. Anything this ticket touches there should gain the tests it never had rather than inheriting the gap.',
    blocked: 'nothing',
    acs: [
      'An article can be drafted, scheduled and published',
      'A draft is not publicly readable',
      'A scheduled article publishes through the existing job queue',
      'Publication is reversible',
      'The paths this ticket touches gain tests',
    ],
  },
  {
    n: '37', slug: 'metadata-and-structured-data',
    title: 'Page metadata and structured data under owner control',
    build: 'Owner-controlled title, description, canonical URL, social preview and structured data for public pages.',
    caution: '**Performance is a functional requirement of this feature, not a quality attribute.** A slow page does not rank, and an unranked page defeats the purpose of writing it.',
    blocked: '35, 36',
    acs: [
      'Title, description, canonical URL and social preview are owner-controlled per page',
      'Structured data is emitted for pages that warrant it',
      'A page with no explicit metadata falls back to a sensible default rather than emitting nothing',
      'Metadata is served with the page, not fetched by the client afterwards',
      'A malformed structured-data configuration is rejected at write time',
    ],
  },
  {
    n: '38', slug: 'mentor-assignment',
    title: 'A mentor is an instructor scoped to specific students',
    build: 'Mentor assignment reusing the per-batch instructor role model from Phase 1, scoped to specific students within a path.',
    caution: '**Reuse the existing per-batch instructor role model rather than inventing a parallel one.** A second role system is the mistake Phase 5 avoided with coding problems and the question bank.',
    blocked: 'nothing',
    acs: [
      'A mentor is assigned to specific students within a path',
      'Assignment reuses the existing instructor role model',
      'A mentor sees only their assigned students',
      'Reassignment preserves the previous relationship\'s history',
      'The owner can read mentor engagement across all mentors',
    ],
  },
  {
    n: '39', slug: 'one-to-one-sessions',
    title: 'Scheduled one-to-ones with a private feedback record',
    build: 'One-to-one sessions reusing the Phase 2 scheduling and session machinery, with a private feedback record per session.',
    caution: '**Private means private to the mentor and the owner.** A feedback record the student can read is a different artefact and would change what mentors write in it.',
    blocked: '38',
    acs: [
      'Sessions reuse the Phase 2 scheduling machinery',
      'Each session carries a private feedback record',
      'The student cannot read the private feedback',
      'A mentor cannot read another mentor\'s session feedback',
      'The owner can see whether sessions are actually happening',
    ],
  },
  {
    n: '40', slug: 'mock-interviews',
    title: 'A mock interview scored against defined competencies',
    build: 'A scheduled session plus a structured feedback form against defined competencies, feeding the Phase 5 skill map.',
    caution: '**Feeds the skill map, so the competency set must map onto existing skills** rather than introducing a second vocabulary that never reconciles with the first.',
    blocked: '38, 39',
    acs: [
      'A mock interview is a scheduled session with a structured feedback form',
      'Feedback is recorded against defined competencies',
      'Competency outcomes feed the existing skill map',
      'A student can read their own interview feedback',
      'An interviewer cannot alter feedback after the student has seen it without it being recorded',
    ],
  },
  {
    n: '41', slug: 'job-board',
    title: 'Openings, applications and status',
    build: 'Openings, applications, status tracking, and employer visibility into portfolios students have published.',
    caution: '**Deliberately minimal. Employer accounts, screening and placement fees are explicitly out of scope** — a different business with different obligations. Employer visibility extends only to portfolios the student has already published.',
    blocked: 'nothing',
    acs: [
      'The owner can post an opening and see who applied',
      'A student can apply and track their application status',
      'Employer visibility extends only to published portfolios',
      'An unpublished portfolio is not reachable through the job board',
      'A student cannot see another student\'s applications',
    ],
  },
  {
    n: '42', slug: 'FRONTEND-doubts-and-answers',
    title: '[FRONTEND] Doubt answering, labelling and escalation',
    build: 'The student surface for asking a doubt, seeing the pending state, reading the answer with working citation links, and escalating in one action.',
    caution: '**The automation label and the citation links are the two things that must not be dropped in presentation.** Both are correctness requirements from the spec, not decoration.',
    blocked: '08, 09, 10, 11',
    frontend: true,
    acs: [
      'A pending answer shows a clear pending state rather than an empty one',
      'The automation label is always rendered on an automated answer',
      'Citation links open the cited lesson',
      'Escalation is one action from the answer',
      'A failed answer shows the human path rather than an error',
    ],
  },
  {
    n: '43', slug: 'FRONTEND-plans-and-summaries',
    title: '[FRONTEND] Study plan and lecture summaries',
    build: 'The daily plan surface and the lecture summary with clickable timestamped chapters that seek the player.',
    caution: '**Chapters must seek the existing player rather than reloading the page.** This depends on the player rebuild in Phase 4 ticket 39.',
    blocked: '17, 22, 23',
    frontend: true,
    acs: [
      'The daily plan renders with its items and their sources',
      'Chapters are clickable and seek the player',
      'Key points are readable without watching the lecture',
      'A lesson with no summary shows nothing rather than an empty shell',
      'The plan reflects regeneration without a manual refresh',
    ],
  },
  {
    n: '44', slug: 'FRONTEND-report-builder',
    title: '[FRONTEND] Report builder and dashboards',
    build: 'The owner surface for composing a report from the dimension and measure palette, saving it, sharing it, scheduling it and exporting it, plus the funnel and retention dashboards.',
    caution: '**The palette comes from the server.** A frontend that hardcodes the dimension list will silently diverge from what the server accepts.',
    blocked: '30, 31, 32, 33, 34',
    frontend: true,
    acs: [
      'The dimension and measure palette is fetched, not hardcoded',
      'A composed report can be saved, shared and scheduled',
      'The funnel renders unknown stages distinctly from zero stages',
      'Retention cohorts render from materialised data',
      'Export produces what the viewer sees',
    ],
  },
  {
    n: '45', slug: 'FRONTEND-page-builder',
    title: '[FRONTEND] Page builder and metadata',
    build: 'The owner surface for composing a page from the block palette — reorder, show, hide — with metadata and structured data fields, and a preview before publishing.',
    caution: '**Per `AUDIT.md` §8.2 this is a section builder, not free-form drag-and-drop.** Same user outcome at a fraction of the cost and risk.',
    blocked: '35, 36, 37',
    frontend: true,
    acs: [
      'Sections can be reordered, shown and hidden',
      'The block palette comes from the server',
      'Metadata and structured data are editable per page',
      'A draft can be previewed before publishing',
      'Publishing is explicit and reversible',
    ],
  },
];

for (const t of tickets) {
  const status = t.frontend ? 'needs-frontend-work' : 'not-started';
  const body = [
    `# ${t.n} - ${t.title}`,
    '',
    `**What to build:** ${t.build}`,
    '',
    t.caution,
    '',
    `**Blocked by:** ${t.blocked}`,
    '',
    `**Status:** ${status}`,
    '',
    ...t.acs.map((ac) => `- [ ] ${ac}`),
    '',
  ].join('\n');
  writeFileSync(`${DIR}/${t.n}-${t.slug}.md`, body, 'utf8');
}

console.log(`wrote ${tickets.length} tickets to ${DIR}`);
